language: php

matrix:
  include:
    - php: 8.1
      env: SYMFONY_VERSION="^6.0"
    - php: 8.1
      env: SYMFONY_VERSION="^7.0"

env:
  global:
    - SYMFONY_VERSION=""

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/framework-bundle "$SYMFONY_VERSION"; fi

install:
  - composer install --prefer-source

before_script:
  - composer self-update
  - composer install --prefer-source
