services:
    sandwich_vies.validator.constraint.vat_number_validator:
        class: Sandwich\ViesBundle\Validator\Constraint\VatNumberValidator
        arguments:
            - "@sandwich_vies.vies_api"
        tags:
            - { name: validator.constraint_validator, alias: vat_number }

    sandwich_vies.vies_api:
        class: DragonBe\Vies\Vies
